=== marcelolynch/xml/TP1/ej5/noticias.dtd
<!ELEMENT rss (channel)>
<!ELEMENT channel (title,link,description,pubDate?,webMaster?,language?,item*)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT link (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT pubDate (#PCDATA)>
	<!ELEMENT webMaster (#PCDATA)>
	<!ELEMENT language (#PCDATA)>
	<!ELEMENT item (title,link,pubDate) >
<!ATTLIST rss version (0.9.1|0.9|1.0|2.0) #REQUIRED>

=== marcelolynch/xml/TP1/ej5/noticias.xml
<?xml version="1.0" ?>
<!DOCTYPE rss SYSTEM "noticias.dtd">
<rss version="1.0">
<channel>
	<title>Marcelo no RSS</title>
	<link>http://chelivery.com</link>

	<description>
		Algun texto descriptivo
	</description>

	<pubDate />
	<webMaster>Chelivr</webMaster>
	<language>es-ar</language>
	
	<item>
		<title>Tit1</title>
		<link>http://etc</link>
		<pubDate />
	</item>
	<item>
		<title>Tit2</title>
		<link>http://etc</link>
		<pubDate />
	</item>
	<item>
		<title>Tit3</title>
		<link>http://etc</link>
		<pubDate>11-01-2014</pubDate>
	</item>
</channel>	
</rss>
