=== marcelolynch/xml/TP1/emails.dtd
<!ELEMENT emails (email*) >
<!ELEMENT email (#PCDATA | (date, header,subject,body))* >
	<!ELEMENT date (#PCDATA)>
	<!ELEMENT header (from,to)>
		<!ELEMENT from (name, address)>
		<!ELEMENT to (name, address)+>
			<!ELEMENT name (firstname,surname)>
			<!ELEMENT firstname (#PCDATA)>
			<!ELEMENT surname (#PCDATA)>
			<!ELEMENT address (#PCDATA)>
	<!ELEMENT subject (#PCDATA) >
	<!ELEMENT body (#PCDATA) >

<!ATTLIST date format CDATA "YYYY-MM-DD">
<!ATTLIST email id ID #IMPLIED
		parent-email IDREF #IMPLIED>
<!ATTLIST header encoding CDATA "UTF-8"
	  mailing-client CDATA #IMPLIED>

=== marcelolynch/xml/TP1/ejercicio2.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE emails SYSTEM "emails.dtd">
<emails>

<email>
	<date format="YYYY-MM-DD">2015-12-12</date>
	<header>
		<from>
			<name>
				<firstname>Marcelo</firstname>
				<surname>Lynchester</surname>
			</name>
			<address>chelo@chelivery.com</address>
		</from>
		<to>
			<name>
				<firstname>El</firstname>
				<surname>Chabon</surname>
			</name>
			<address>chaboncin@dominio.com</address>
		</to>
	</header>
	<subject>
		Prueba!!
	</subject>
	<body>
		Querido Chabon:
		Ojala te mueras
		Un saludo
	</body>
</email>
	
<email>
	<date format="YYYY-MM-DD">2015-21-12</date>
	<header>
		<from>
			<name>
				<firstname>Marcelo</firstname>
				<surname>Lynchester</surname>
			</name>
			<address>chelo@chelivery.com</address>
		</from>
		<to>
			<name>
				<firstname>El</firstname>
				<surname>Chabon</surname>
			</name>
			<address>chaboncin@dominio.com</address>
		</to>
	</header>
	SAKDJSAKLDJ3304923049SKADJJ235
	<subject>
		Prueba!!
	</subject>
	<body>
		probando
	</body>
</email>

<email id="C1">
	alfanum23492349239
	<date format="YYYY-MM-DD">2015-12-12</date>
	<header>
		<from>
			<name>
				<firstname>Marcelo</firstname>
				<surname>Lynchester</surname>
			</name>
			<address>chelo@chelivery.com</address>
		</from>
		<to>
			<name>
				<firstname>El</firstname>
				<surname>Chabon</surname>
			</name>
			<address>chaboncin@dominio.com</address>
		</to>

	</header>
	<subject>
		Prueba!!
	</subject>
		 
	<body>
		Querido Chabon:
		Ojala te mueras
		Un saludo
	</body>
</email>
</emails>
