=== marcelolynch/xml/TP2/ej3/emails.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="personData">
		<xsd:sequence>
		<xsd:element name="name">
			<xsd:complexType>
				<xsd:sequence>
				<xsd:element name="firstname" type="xsd:string" />
				<xsd:element name="surname" minOccurs="0" type="xsd:string" />
				</xsd:sequence>
			</xsd:complexType>
		</xsd:element>	
		<xsd:element name="address">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:pattern value="(\w[\w_+-.]*)?\w@\w+(\.([\w]+(-+[\w]+)*))*\.[A-Za-z]+" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>
	
		</xsd:sequence>
	</xsd:complexType>
	

	<xsd:element name="emails">
	<xsd:complexType>
	<xsd:sequence>
	<xsd:element name="email" maxOccurs="unbounded">
		<xsd:complexType mixed="true" >
			<xsd:sequence>
				<xsd:element name="date" type="xsd:date" />
			
				<xsd:element name="header">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="from" type="personData" />
							<xsd:element name="to" type="personData" />
						</xsd:sequence>
					<xsd:attribute name="encoding" default="UTF-8">
						<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="UTF-8" />
							<xsd:enumeration value="UTF-16" />
							<xsd:enumeration value="ISO-8856-1" />
						</xsd:restriction> 
						</xsd:simpleType>
					</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
					
				<xsd:element name="subject">
					<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="256" />
					</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
			
				<xsd:element name="body" type="xsd:string" />
			</xsd:sequence>	

			<xsd:attribute name="id" type="xsd:ID" use="required" />
			<xsd:attribute name="replies_to" type="xsd:IDREF" />
		</xsd:complexType>
	</xsd:element>

	</xsd:sequence>
	</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== marcelolynch/xml/TP2/ej3/emails.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<emails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="emails.xsd">
<email id="abcd">
	<date>2015-12-12</date>
	<header>
		<from>
			<name>
				<firstname>Marcelo</firstname>
				<surname>Lynchester</surname>
			</name>
			<address>chelo@c929.a.helivery.edu-copy.com</address>
		</from>
		<to>
			<name>
				<firstname>El</firstname>
				<surname>Chabon</surname>
			</name>
			<address>chaboncin@dominio.com</address>
		</to>
	</header>
	<subject>Prueba!!</subject>
	<body>
		Querido Chabon:
		Ojala te mueras
		Un saludo
	</body>
</email>
	
<email id="C3">
	<date>2015-11-12</date>
	<header>
		<from>
			<name>
				<firstname>Marcelo</firstname>
				<surname>Lynchester</surname>
			</name>
			<address>chelo@chelivery.com</address>
		</from>
		<to>
			<name>
				<firstname>El</firstname>
				<surname>Chabon</surname>
			</name>
			<address>chaboncin@dominio.com</address>
		</to>
	</header>
	SAKDJSAKLDJ3304923049SKADJJ235
	<subject>
		Prueba!!
	</subject>
	<body>
		probando
	</body>
</email>

<email id="C1">
	alfanum23492349239
	<date>2015-12-12</date>
	<header encoding="UTF-16">
		<from>
			<name>
				<firstname>Marcelo</firstname>
				<surname>Lynchester</surname>
			</name>
			<address>chelo@chelivery.com</address>
		</from>
		<to>
			<name>
				<firstname>El</firstname>
				<surname>Chabon</surname>
			</name>
			<address>chaboncin@dominio.com</address>
		</to>

	</header>
	<subject>
		Prueba!!
	</subject>
		 
	<body>
		Querido Chabon:
		Ojala te mueras
		Un saludo
	</body>
</email>
</emails>
